version: '3'

services:
  drupal:
    image: drupal
    ports:
      - '8080:80'
    networks:
      - mynet
    volumes:
      - drupal-modules:/var/www/html/modules
      - drupal-profiles:/var/www/html/profiles
      - drupal-sites:/var/www/html/sites
      - drupal-themes:/var/www/html/themes
  psql1:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=123456
    networks:
      - mynet
    volumes:
      - pg-data:/var/lib/postgresql/data

networks:
  mynet:

volumes:
  drupal-modules:
  drupal-profiles:
  drupal-sites:
  drupal-themes:
  pg-data:
